---
- name: "Configure timezone for Windows machines"
  ansible.builtin.include_tasks: windows.yml
  when: ansible_facts['os_family'] == "Windows"

- name: "Configure timezone for Linux machines"
  ansible.builtin.include_tasks: linux.yml
  when: ansible_facts['os_family'] == "Linux"
