---
- name: "Assert that Windows timezone vars are defined"
  ansible.builtin.assert:
    that:
      - windows_tz is defined
    fail_msg: "Not all required parameters for Windows timezone are set"
    success_msg: "All required parameters for Windows timezone are set"

- name: "Set timezone to {{ windows_tz }}"
  win_timezone:
    timezone: "{{ windows_tz }}"
