---
all:
  children:
    linux_servers:
      children:
        ansible_control_nodes:
          hosts:
            azdo-controlnode:

    windows_servers:
      children:
        domain_controllers:
          hosts:
            azdo-adserver:
        app:
          hosts:
            appserver01:
              role: azdo_primary
        database_servers:
          hosts:
            azdo-sqlserver:
