---
all:
  children:
    linux_servers:
      children:

    windows_servers:
      children:
        domain_controllers:
          hosts:
            azdo-adserver:
              vmx_file_path: "D:\\Virtual Machines\\AZDO-ADServer\\AZDO-ADServer.vmx"
        app:
          hosts:
            appserver01:
              vmx_file_path: "D:\\Virtual Machines\\appserver01\\appserver01.vmx"
              role: azdo_first
            appserver02:
              vmx_file_path: "D:\\Virtual Machines\\appserver02\\appserver02.vmx"
              role: azdo_additional
        database_servers:
          hosts:
            azdo-sqlserver:
              vmx_file_path: "D:\\Virtual Machines\\AZDO-SQLServer\\AZDO-SQLServer.vmx"
