---
# Run unattended installation of Azure Devops Server
# Database provisioning occurs under the user running the configuration tool, not the configured service account
# This means the user running the configuration tool (ie. the ansible user) needs to have sufficient privileges on SQL
# Check documentation: https://learn.microsoft.com/en-us/azure/devops/server/command-line/tfsconfig-cmd?view=azure-devops-2022#unattend

- name: "Check status of IsConfigured regkey"
  ansible.windows.win_reg_stat:
    path: "{{ azdo_apptier_regkey }}"
    name: "IsConfigured"
  register: isconfigured

- name: "Set azdo_build_unattendfile_args variable for the first node of a cluster"
  set_fact:
    azdo_build_unattendfile_args: "{{ azdo_build_unattendfile_first_args }}"
  when: role == "azdo_first"

- name: "Set azdo_build_unattendfile_args variable for additional nodes of a cluster"
  set_fact:
    azdo_build_unattendfile_args: "{{ azdo_build_unattendfile_additional_args }}"
  when: role == "azdo_additional"

- name: "Installing Azure Devops Server"
  when:
    - not isconfigured.exists
  block:

    - name: "Create unattend file"
      ansible.windows.win_shell: |
        $arguments = "{{ azdo_build_unattendfile_args | join(' ') }}"
        Start-Process -NoNewWindow -PassThru -Wait -FilePath "{{ azdo_install_path }}\\Tools\\TfsConfig.exe" -ArgumentList $arguments
  
    - name: "Add ServiceAccountPassword to unattend file"
      community.windows.win_lineinfile:
        path: "{{ azdo_build_unattendfile_path }}"
        line: "ServiceAccountPassword={{ azdo_serviceaccount_password }}"
  
    - name: "Run unattend installation of Azure DevOps Server"
      ansible.windows.win_shell: >
        Start-Process -NoNewWindow -PassThru -Wait -FilePath "{{ azdo_install_path }}\\Tools\TfsConfig.exe" -ArgumentList "unattend /configure /unattendfile:`"{{ azdo_build_unattendfile_path }}`" /continue"
  
    - name: "Remove unattend file"
      community.windows.win_lineinfile:
        path: "{{ azdo_build_unattendfile_path }}"
        state: absent
