---
- name: "Get running VMs"
  ansible.builtin.shell:
   cmd: set -o pipefail && vmrun.exe -T ws list | grep -F "{{ vmx_file_path }}" || true
   executable: /bin/bash
  register: vm_list
  changed_when: vm_list.stdout | length == 0
