---
- name: Play for shutting down lab environment
  hosts: all
  gather_facts: false

  tasks:
   - name: "Shutdown lab environment"
     delegate_to: localhost

     block:
      - name: "Include task to get running VMs"
        ansible.builtin.include_tasks: ../templates/get-running-vms.yml

      - name: "Shutdown lab VMs"
        ansible.builtin.shell:
         cmd: set -o pipefail && vmrun.exe -T ws stop "{{ vmx_file_path }}"
         executable: /bin/bash
        when: vm_list.stdout | length > 0
