---
- name: Play for starting lab environment
  hosts: all
  gather_facts: false

  tasks:
   - name: "Start lab environment"
     delegate_to: localhost

     block:
      - name: "Include task to get running VMs"
        ansible.builtin.include_tasks: ../templates/get-running-vms.yml

      - name: "Start Lab VMs"
        throttle: 1
        ansible.builtin.shell:
         cmd: set -o pipefail && vmrun.exe -T ws start "{{ vmx_file_path }}" nogui
         executable: /bin/bash
        when: vm_list.stdout | length == 0

# Test with these shell commands: start-lab && sleep 60 && shutdown-lab
