---
- name: Play for starting lab environment
  hosts: all
  gather_facts: false

  tasks:
   - name: "Start lab environment"
     delegate_to: localhost

     block:
      - name: "Include task to get running VMs"
        ansible.builtin.include_tasks: ../templates/get-running-vms.yml

      - name: "Start Lab VMs"
        throttle: 1
        ansible.builtin.shell:
         cmd: set -o pipefail && vmrun.exe -T ws start "{{ vmx_file_path }}" nogui
         executable: /bin/bash
        when: vm_list.stdout | length == 0

      - name: "Check VMware Tools status"
        ansible.builtin.shell:
         cmd: set -o pipefail && vmrun.exe -T ws checkToolsState "{{ vmx_file_path }}" || true
         executable: /bin/bash
        register: vmtools_status
        async: 120   # Maximaal 120 seconden laten lopen
        poll: 5      # Controleer elke 5 seconden
        retries: 20  # Herhaal de controle max. 10 keer
        delay: 5     # Wacht 5 seconden tussen pogingen
        until: "'running' in vmtools_status.stdout"
        changed_when: false

# Test with these shell commands: start-lab && sleep 60 && shutdown-lab
