---
- hosts: all
  gather_facts: false
 
  tasks:
  - name: "Start lab environment"
    delegate_to: localhost

    block:
    - name: "Check running lab VMs"
      ansible.builtin.shell: vmrun.exe -T ws list | grep -F "{{ vmx_file_path }}" || true
      register: vm_list
      changed_when: vm_list.stdout | length == 0
  
    - name: "Start Lab VMs"
      ansible.builtin.shell: vmrun.exe -T ws start "{{ vmx_file_path }}" nogui
      when: vm_list.stdout | length == 0
